### ISSUE TITLE
Minor feedbacks on the corner plot

### ISSUE THREAD

**Issue by sylacour** [sblunt/orbitize#169]
Dear Sarah (and/or others).

Here are a small remarks on the orbitize corner plot function:

1- First, if I put rv_time_series = True, the colorbar does not show up. Even if I put show_colorbar = True

2- Second, it always open a new window. Is there a way to specify which figure to put it in?

3- Third, the label “epoch” is misleading. In the data table, the epoch is in MJD. Here, it is in year. I got quite confused because of that. Maybe the X axis should be renamed (Epoch [year]).

4- Fourth, if a parameter is constrained, the corner plot crash because it cannot find a range:
$ corner_plot_fig = results.plot_corner()
Traceback (most recent call last):
  File "/Users/slacour/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-724dea050da8>", line 1, in <module>
    corner_plot_fig = results.plot_corner()
  File "/Users/slacour/ONGOING/GitsVarious/orbitize/orbitize/results.py", line 295, in plot_corner
    figure = corner.corner(samples, **corner_kwargs)
  File "/Users/slacour/opt/anaconda3/lib/python3.7/site-packages/corner/corner.py", line 173, in corner
    "{0}".format, np.arange(len(m))[m]))))
ValueError: It looks like the parameter(s) in column(s) 15, 16 have no dynamic range. Please provide a `range` argument.

Cheers, and thanks again for this useful tool.
S.

**Comment by sylacour** [comment]
Haha, my mistake, Jason already opened a bug report!!
